import { Helmet } from 'react-helmet-async';
import { BriefcaseBusiness, CalendarDays, CheckCircle2, Code2, GraduationCap, Mail, MapPin, Phone, Target, UserRound } from 'lucide-react';
import { useConfig } from '../hooks/useConfig';
import { resolveAssetUrl } from '../lib/assets';

const toolColors = ['bg-blue-50 text-blue-700', 'bg-emerald-50 text-emerald-700', 'bg-amber-50 text-amber-700', 'bg-violet-50 text-violet-700', 'bg-rose-50 text-rose-700'];

function SectionTitle({ icon: Icon, children }) {
  return <h2 className="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-slate-100"><Icon size={19} className="text-blue-600" />{children}</h2>;
}

function Card({ children, className = '' }) {
  return <section className={`rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800 ${className}`}>{children}</section>;
}

export default function AboutPage() {
  const { site, owner, skills = {}, about = {}, experiences = [] } = useConfig();
  const technical = skills.technical || [];
  const soft = skills.soft || [];
  const tools = about.tools || {};
  const education = Array.isArray(about.education)
    ? (about.education.length ? about.education : experiences.filter((item) => item.type === 'education'))
    : (about.education?.organization ? [about.education] : experiences.filter((item) => item.type === 'education'));
  const work = experiences.filter((item) => item.type !== 'education');
  const contact = owner.contact || {};

  return <>
    <Helmet><title>{`Giới thiệu | ${site.name}`}</title><meta name="description" content={(owner.bio || '').slice(0, 160)} /><link rel="canonical" href={`${site.url}/#/about`} /></Helmet>
    <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <Card className="overflow-hidden bg-gradient-to-br from-blue-50 via-white to-sky-50 p-0 dark:from-slate-800 dark:via-slate-800 dark:to-slate-900">
        <div className="grid gap-6 p-6 lg:grid-cols-[1.35fr_1fr_1fr] lg:items-center lg:p-7">
          <div className="flex flex-col items-center gap-5 text-center sm:flex-row sm:text-left"><img src={resolveAssetUrl(owner.avatar)} alt={owner.name} className="h-28 w-28 shrink-0 rounded-full object-cover ring-4 ring-blue-500/20" /><div><p className="mb-1 text-sm font-semibold text-blue-600">{about.focus || owner.title}</p><h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100 sm:text-3xl">{owner.name}</h1><p className="mt-2 text-sm italic text-slate-500 dark:text-slate-400">“{owner.motto}”</p><div className="mt-4 flex flex-wrap justify-center gap-2 sm:justify-start">{owner.social?.github && <a href={owner.social.github} target="_blank" rel="noreferrer" className="rounded-md bg-slate-900 px-3 py-1.5 text-xs font-semibold text-white">GitHub</a>}{owner.social?.linkedin && <a href={owner.social.linkedin} target="_blank" rel="noreferrer" className="rounded-md bg-blue-600 px-3 py-1.5 text-xs font-semibold text-white">LinkedIn</a>}{owner.social?.facebook && <a href={owner.social.facebook} target="_blank" rel="noreferrer" className="rounded-md bg-blue-500 px-3 py-1.5 text-xs font-semibold text-white">Facebook</a>}{contact.zalo && <a href={`https://zalo.me/${String(contact.zalo).replace(/\D/g, '')}`} target="_blank" rel="noreferrer" className="rounded-md border border-blue-400 px-3 py-1.5 text-xs font-semibold text-blue-600">Zalo</a>}</div></div></div>
          <div className="space-y-3 border-slate-200 text-sm dark:border-slate-700 lg:border-l lg:pl-6"><p className="flex gap-3 text-slate-600 dark:text-slate-300"><CalendarDays size={16} className="shrink-0 text-blue-600" />Ngày sinh <span className="font-medium text-slate-900 dark:text-slate-100">{about.birthDate || 'Chưa cập nhật'}</span></p><p className="flex gap-3 text-slate-600 dark:text-slate-300"><MapPin size={16} className="shrink-0 text-blue-600" />Địa chỉ <span className="font-medium text-slate-900 dark:text-slate-100">{owner.location}</span></p><p className="flex gap-3 text-slate-600 dark:text-slate-300"><Mail size={16} className="shrink-0 text-blue-600" />Email <span className="break-all font-medium text-slate-900 dark:text-slate-100">{owner.email}</span></p><p className="flex gap-3 text-slate-600 dark:text-slate-300"><Phone size={16} className="shrink-0 text-blue-600" />Điện thoại <span className="font-medium text-slate-900 dark:text-slate-100">{contact.phone || contact.zalo || 'Chưa cập nhật'}</span></p></div>
          <div className="rounded-lg bg-blue-100/70 p-5 dark:bg-blue-950/30"><SectionTitle icon={Target}>Định hướng</SectionTitle><p className="mt-3 text-sm font-semibold text-blue-800 dark:text-blue-300">{about.focus || owner.title}</p><p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{about.direction}</p></div>
        </div>
      </Card>
      <div className="mt-3 grid gap-3 lg:grid-cols-[1fr_1.65fr]"><Card><SectionTitle icon={UserRound}>Về tôi</SectionTitle><div className="mt-4 space-y-3 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{(owner.bio || '').split(/\n+/).filter(Boolean).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></Card><Card><SectionTitle icon={Code2}>Kỹ năng kỹ thuật</SectionTitle><div className="mt-4 grid gap-x-8 gap-y-4 sm:grid-cols-2">{technical.map((skill) => <div key={skill.name}><div className="mb-1 flex justify-between text-xs font-semibold text-slate-600 dark:text-slate-300"><span>{skill.name}</span><span className="text-blue-600">{skill.level}%</span></div><div className="h-1.5 rounded-full bg-slate-100 dark:bg-slate-700"><div className="h-full rounded-full bg-blue-500" style={{ width: `${Math.min(100, Math.max(0, skill.level || 0))}%` }} /></div></div>)}</div><div className="mt-6"><h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Kỹ năng mềm</h3><div className="mt-3 flex flex-wrap gap-2">{soft.map((item) => <span key={item} className="rounded-full bg-blue-50 px-3 py-1.5 text-xs text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">⌄ {item}</span>)}</div></div></Card></div>
      <Card className="mt-3"><SectionTitle icon={Code2}>Công nghệ & Công cụ</SectionTitle><div className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(tools).map(([group, items], index) => <div key={group}><p className="mb-2 text-xs font-semibold text-slate-500 dark:text-slate-400">{group}</p><div className="flex flex-wrap gap-2">{(items || []).map((item) => <span key={item} className={`rounded-md px-2.5 py-1.5 text-xs font-medium ${toolColors[index % toolColors.length]}`}>{item}</span>)}</div></div>)}</div></Card>
      <div className="mt-3 grid gap-3 lg:grid-cols-[1.35fr_.75fr_1fr]"><Card><SectionTitle icon={BriefcaseBusiness}>Kinh nghiệm làm việc</SectionTitle><div className="mt-4 space-y-5 border-l-2 border-blue-100 pl-5 dark:border-blue-950">{work.map((item) => <article key={`${item.organization}-${item.startDate}`} className="relative"><span className="absolute -left-[1.62rem] top-1 h-2.5 w-2.5 rounded-full bg-blue-500 ring-4 ring-white dark:ring-slate-800" /><p className="text-xs font-semibold text-blue-600">{item.startDate || ''} - {item.endDate || 'Nay'}</p><h3 className="mt-1 text-sm font-bold text-slate-800 dark:text-slate-100">{item.role}</h3><p className="text-xs font-medium text-slate-500">{item.organization}</p><p className="mt-1 text-xs leading-relaxed text-slate-600 dark:text-slate-300">{item.description}</p></article>)}</div></Card><Card><SectionTitle icon={GraduationCap}>Học vấn</SectionTitle><div className="mt-4 space-y-5">{education.map((item) => <article key={`${item.organization}-${item.period || item.startDate}`}><h3 className="text-sm font-bold text-slate-800 dark:text-slate-100">{item.organization}</h3><p className="mt-1 text-xs text-blue-600">{item.role} {item.period && `· ${item.period}`}</p><p className="mt-2 text-xs leading-relaxed text-slate-600 dark:text-slate-300">{item.description}</p></article>)}</div></Card><Card><SectionTitle icon={Target}>Mục tiêu & Định hướng</SectionTitle><ul className="mt-4 space-y-3">{(about.goals || []).map((goal) => <li key={goal} className="flex gap-2 text-sm text-slate-600 dark:text-slate-300"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-blue-600" />{goal}</li>)}</ul><blockquote className="mt-6 rounded-lg bg-blue-50 p-4 text-center text-xs italic text-blue-700 dark:bg-blue-950/30 dark:text-blue-300">“{about.quote}”</blockquote></Card></div>
    </main>
  </>;
}
